/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the caller. First call of a session provisions the user (JIT) and emits identity.user.logged_in.v1. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Directory search for inviting members. Returns only ACTIVE users with an ACTIVE membership. */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organization_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        /** @description ORG_ADMIN of the organization or PLATFORM_ADMIN only. */
        get: operations["listOrganizationMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organization_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: components["parameters"]["OrganizationId"];
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description ORG_ADMIN / PLATFORM_ADMIN. Emits identity.membership.changed.v1. Disabling a membership triggers grant revocation (MEMBERSHIP_DISABLED). */
        patch: operations["updateOrganizationMember"];
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Projects the caller is a member of, plus PUBLIC projects when `scope=discover`. */
        get: operations["listProjects"];
        put?: never;
        /** @description Caller becomes PROJECT_OWNER; caller's organization becomes lead organization. */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** @description Members only. Non-members get 404 for PRIVATE and 403 FORBIDDEN for PUBLIC. */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description PROJECT_OWNER / PROJECT_ADMIN. */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{project_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description PROJECT_OWNER only. Emits project.archived.v1; governance revokes all project-scoped grants. */
        post: operations["archiveProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listProjectMembers"];
        put?: never;
        /** @description PROJECT_OWNER / PROJECT_ADMIN. Cross-organization users allowed. P0 adds directly (ACTIVE) and notifies (D-007). */
        post: operations["addProjectMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description PROJECT_OWNER / PROJECT_ADMIN, or the member themself (leave). Emits project.member.removed.v1. */
        delete: operations["removeProjectMember"];
        options?: never;
        head?: never;
        patch: operations["updateProjectMemberRole"];
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OpenSearch-backed metadata search. Visibility per D-012. Search p95 < 1.5s. */
        get: operations["searchDatasets"];
        put?: never;
        /** @description DATA_STEWARD of owner_organization_id only (D-013). */
        post: operations["createDataset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: components["parameters"]["DatasetId"];
            };
            cookie?: never;
        };
        get: operations["getDataset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Owner-org DATA_STEWARD. Policy/access_level changes emit POLICY_CHANGED events. Existing grants are not altered by policy changes. */
        patch: operations["updateDataset"];
        trace?: never;
    };
    "/datasets/{dataset_id}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: components["parameters"]["DatasetId"];
            };
            cookie?: never;
        };
        /** @description Read model consumed by governance and web. */
        get: operations["getDatasetPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: components["parameters"]["DatasetId"];
            };
            cookie?: never;
        };
        /** @description Non-stewards see only PUBLISHED versions. */
        get: operations["listDatasetVersions"];
        put?: never;
        /** @description Owner-org DATA_STEWARD. Creates a DRAFT version. */
        post: operations["createDatasetVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        /** @description Includes file manifest (names, sizes, checksums) - manifest is metadata, not data. */
        get: operations["getDatasetVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-versions/{version_id}/upload-session": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Owner-org DATA_STEWARD, DRAFT version only. Returns presigned PUT URLs (multipart above 64 MiB). Session TTL 1h. */
        post: operations["createUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload-sessions/{upload_session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_session_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        /** @description Owner-org DATA_STEWARD. Poll file verification status. Presigned URLs are omitted after the session is COMPLETED/EXPIRED. */
        get: operations["getUploadSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-versions/{version_id}/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
                file_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Owner-org DATA_STEWARD, DRAFT version only. Removes manifest row and stored object. */
        delete: operations["deleteDraftFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload-sessions/{upload_session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_session_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Completes multipart uploads and verifies size + sha256 (D-014). Files <= 256 MiB are verified synchronously (VERIFIED/FAILED in the response); larger files return UPLOADED and are verified asynchronously by the worker — poll getUploadSession. Files failing verification are marked FAILED with failure_code and deleted from storage. */
        post: operations["completeUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-versions/{version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Owner-org DATA_STEWARD. Requires >=1 file and all files VERIFIED. Version becomes immutable. Emits catalog.dataset.version_published.v1. */
        post: operations["publishDatasetVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccessRequests"];
        put?: never;
        /** @description Creates in SUBMITTED (D-015). Caller must be an ACTIVE member of project_id with role other than VIEWER (VIEWER -> FORBIDDEN). Project must be ACTIVE. */
        post: operations["createAccessRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/{access_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        /** @description Visible to requester and owner-org DATA_STEWARD/ORG_ADMIN. Read-only, no state change (D-025). */
        get: operations["getAccessRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/{access_request_id}/start-review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Owner-org DATA_STEWARD (not the requester). SUBMITTED -> UNDER_REVIEW, emits governance.access.review_started.v1. Idempotent for UNDER_REVIEW. Optional — approve/reject/request-changes also accept SUBMITTED (D-025). */
        post: operations["startAccessReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/{access_request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Owner-org DATA_STEWARD. Allowed from SUBMITTED/UNDER_REVIEW. Creates ACTIVE grant. */
        post: operations["approveAccessRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/{access_request_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejectAccessRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/{access_request_id}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestAccessChanges"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/{access_request_id}/resubmit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requester only, from CHANGE_REQUESTED. Fields omitted keep previous values. */
        post: operations["resubmitAccessRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/{access_request_id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requester only, from SUBMITTED/UNDER_REVIEW/CHANGE_REQUESTED. */
        post: operations["withdrawAccessRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccessGrants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-grants/{access_grant_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_grant_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Owner-org DATA_STEWARD / ORG_ADMIN. Effective immediately for new download sessions. */
        post: operations["revokeAccessGrant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-versions/{version_id}/download-session": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Order (01_ARCHITECTURE §7): version PUBLISHED → basis (PUBLIC / OWNER_ORGANIZATION / GRANT) → for GRANT: active grant for (caller, project, dataset),
         *     operation READ, not expired, caller still ACTIVE project member → OPA decision → presigned GET URLs (TTL 300s).
         *     Every outcome is audited (authorized/denied).
         */
        post: operations["createDownloadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReadinessProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-versions/{version_id}/readiness-validations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Owner-org DATA_STEWARD. PUBLISHED versions only. Same input fingerprint + profile version returns the existing COMPLETED result (200) instead of re-running. */
        post: operations["startReadinessValidation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-versions/{version_id}/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        /** @description Latest validation per profile for this version. Visible to anyone who can see the dataset metadata. No results yet -> 200 with empty items; profile_id given but never run -> 404 READINESS_NOT_AVAILABLE. */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Scope: PLATFORM_ADMIN all; ORG_ADMIN/DATA_STEWARD events where actor org or resource owner org is theirs;
         *     other users: own actions, plus events of projects they are members of when project_id is given.
         */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Id: string;
        /** Format: date-time */
        Timestamp: string;
        ErrorEnvelope: {
            error: {
                /** @example ACCESS_GRANT_EXPIRED */
                code: string;
                message: string;
                trace_id: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        PageEnvelope: {
            items: unknown[];
            page: {
                next_cursor?: string | null;
                has_more: boolean;
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded" | "down";
            checks?: {
                [key: string]: "ok" | "down";
            };
        };
        /** @enum {string} */
        ActiveStatus: "ACTIVE" | "DISABLED";
        /** @enum {string} */
        OrganizationType: "RESEARCH_INSTITUTE" | "UNIVERSITY" | "COMPANY" | "PLATFORM_OPERATOR";
        /** @enum {string} */
        OrgRole: "ORG_ADMIN" | "DATA_STEWARD" | "RESOURCE_MANAGER";
        /** @enum {string} */
        PlatformRole: "PLATFORM_ADMIN";
        /** @enum {string} */
        ProjectRole: "PROJECT_OWNER" | "PROJECT_ADMIN" | "RESEARCHER" | "VIEWER";
        /** @enum {string} */
        ProjectStatus: "ACTIVE" | "ARCHIVED";
        /** @enum {string} */
        ProjectVisibility: "PRIVATE" | "PUBLIC";
        /** @enum {string} */
        AccessLevel: "PUBLIC" | "INTERNAL" | "CONTROLLED" | "SENSITIVE";
        /** @enum {string} */
        Purpose: "ACADEMIC_RESEARCH" | "AI_TRAINING" | "COMMERCIAL_RESEARCH" | "EDUCATION" | "PUBLIC_INTEREST";
        /**
         * @description P0 grantable: READ only (D-009)
         * @enum {string}
         */
        Operation: "READ" | "COMPUTE" | "WRITE";
        /** @enum {string} */
        DatasetStatus: "ACTIVE" | "WITHDRAWN";
        /** @enum {string} */
        DatasetVersionStatus: "DRAFT" | "PUBLISHED" | "WITHDRAWN";
        /** @enum {string} */
        FileStatus: "PENDING" | "UPLOADED" | "VERIFIED" | "FAILED";
        /** @enum {string} */
        AccessRequestStatus: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "CHANGE_REQUESTED" | "APPROVED" | "REJECTED" | "WITHDRAWN";
        /** @enum {string} */
        AccessGrantStatus: "ACTIVE" | "EXPIRED" | "REVOKED";
        /** @enum {string} */
        ReadinessRunStatus: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED";
        /** @enum {string} */
        ReadinessOverall: "PASS" | "WARNING" | "FAIL";
        /** @enum {string} */
        ReadinessCheckStatus: "PASS" | "WARNING" | "FAIL" | "NOT_APPLICABLE";
        /** @enum {string} */
        ResourceType: "USER" | "ORGANIZATION" | "MEMBERSHIP" | "PROJECT" | "PROJECT_MEMBER" | "DATASET" | "DATASET_VERSION" | "DATASET_FILE" | "ACCESS_REQUEST" | "ACCESS_GRANT" | "READINESS_VALIDATION";
        /** @enum {string} */
        AuditAction: "LOGIN" | "USER_CREATED" | "ORGANIZATION_CREATED" | "ADMIN_ROLE_CHANGED" | "PROJECT_CREATED" | "PROJECT_ARCHIVED" | "PROJECT_MEMBER_ADDED" | "PROJECT_MEMBER_REMOVED" | "PROJECT_MEMBER_ROLE_CHANGED" | "DATASET_CREATED" | "DATASET_VERSION_PUBLISHED" | "POLICY_CHANGED" | "ACCESS_REQUESTED" | "ACCESS_REVIEW_STARTED" | "ACCESS_APPROVED" | "ACCESS_REJECTED" | "ACCESS_CHANGES_REQUESTED" | "ACCESS_WITHDRAWN" | "ACCESS_REVOKED" | "ACCESS_EXPIRED" | "FILE_DOWNLOADED" | "DOWNLOAD_DENIED" | "READINESS_VALIDATION_COMPLETED";
        /** @enum {string} */
        NotificationType: "PROJECT_INVITATION" | "ACCESS_SUBMITTED" | "ACCESS_APPROVED" | "ACCESS_REJECTED" | "ACCESS_CHANGES_REQUESTED" | "ACCESS_EXPIRING" | "ACCESS_REVOKED" | "DATASET_PUBLISHED";
        IdentityPublicProfile: {
            user_id: components["schemas"]["Id"];
            display_name: string;
            organization_id: components["schemas"]["Id"];
            organization_name?: string;
            status: components["schemas"]["ActiveStatus"];
        };
        OrganizationSummary: {
            organization_id: components["schemas"]["Id"];
            /** @example inst-a */
            code: string;
            name: string;
            type: components["schemas"]["OrganizationType"];
        };
        Organization: components["schemas"]["OrganizationSummary"] & {
            /** @description P2 extension */
            ror_id?: string | null;
            /** Format: uri */
            homepage_url?: string | null;
            member_count?: number;
            dataset_count?: number;
            created_at?: components["schemas"]["Timestamp"];
        };
        OrganizationMembership: {
            user_id: components["schemas"]["Id"];
            organization_id: components["schemas"]["Id"];
            display_name?: string;
            /** Format: email */
            email?: string;
            roles: components["schemas"]["OrgRole"][];
            status: components["schemas"]["ActiveStatus"];
            updated_at?: components["schemas"]["Timestamp"];
        };
        Me: {
            user_id: components["schemas"]["Id"];
            display_name: string;
            /** Format: email */
            email: string;
            status: components["schemas"]["ActiveStatus"];
            organization: components["schemas"]["OrganizationSummary"];
            org_roles: components["schemas"]["OrgRole"][];
            platform_roles: components["schemas"]["PlatformRole"][];
        };
        ProjectSummary: {
            project_id: components["schemas"]["Id"];
            name: string;
            status: components["schemas"]["ProjectStatus"];
            visibility: components["schemas"]["ProjectVisibility"];
            lead_organization_id: components["schemas"]["Id"];
            my_role?: components["schemas"]["ProjectRole"] | null;
            member_count?: number;
            updated_at?: components["schemas"]["Timestamp"];
        };
        Project: components["schemas"]["ProjectSummary"] & {
            description: string;
            keywords?: string[];
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            organizations: {
                organization_id: components["schemas"]["Id"];
                name?: string;
                /**
                 * @description PARTNER rows are derived from members' organizations
                 * @enum {string}
                 */
                role: "LEAD" | "PARTNER";
            }[];
            created_by?: components["schemas"]["Id"];
            created_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            archived_at?: string | null;
        };
        ProjectCreate: {
            name: string;
            description: string;
            visibility?: components["schemas"]["ProjectVisibility"];
            keywords?: string[];
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        ProjectUpdate: {
            name?: string;
            description?: string;
            visibility?: components["schemas"]["ProjectVisibility"];
            keywords?: string[];
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
        };
        ProjectMember: {
            project_id: components["schemas"]["Id"];
            user_id: components["schemas"]["Id"];
            display_name?: string;
            organization_id: components["schemas"]["Id"];
            organization_name?: string;
            role: components["schemas"]["ProjectRole"];
            joined_at: components["schemas"]["Timestamp"];
            added_by?: components["schemas"]["Id"];
        };
        DatasetPolicyView: {
            dataset_id: components["schemas"]["Id"];
            owner_organization_id: components["schemas"]["Id"];
            access_level: components["schemas"]["AccessLevel"];
            allowed_purposes: components["schemas"]["Purpose"][];
            /** @description P0: always true for CONTROLLED/SENSITIVE; ignored for PUBLIC/INTERNAL */
            approval_required: boolean;
            /** @description SENSITIVE <= 30 */
            max_grant_days: number;
        };
        DatasetCreate: {
            owner_organization_id: components["schemas"]["Id"];
            title: string;
            description: string;
            keywords?: string[];
            /**
             * @example materials
             * @example bio
             * @example energy
             */
            domain?: string;
            access_level: components["schemas"]["AccessLevel"];
            /**
             * @example CC-BY-4.0
             * @example NAIS-CONTROLLED-1.0
             */
            license: string;
            usage_policy?: string;
            allowed_purposes: components["schemas"]["Purpose"][];
            /** @default 180 */
            max_grant_days: number;
            /** Format: email */
            contact_email?: string;
            /** @description How the data was produced (instrument, method, source) */
            provenance?: string;
        };
        DatasetUpdate: {
            title?: string;
            description?: string;
            keywords?: string[];
            domain?: string;
            access_level?: components["schemas"]["AccessLevel"];
            license?: string;
            usage_policy?: string;
            allowed_purposes?: components["schemas"]["Purpose"][];
            max_grant_days?: number;
            /** Format: email */
            contact_email?: string;
            provenance?: string;
            status?: components["schemas"]["DatasetStatus"];
        };
        Dataset: {
            dataset_id: components["schemas"]["Id"];
            owner_organization_id: components["schemas"]["Id"];
            owner_organization_name?: string;
            title: string;
            description: string;
            keywords?: string[];
            domain?: string | null;
            access_level: components["schemas"]["AccessLevel"];
            license: string;
            usage_policy?: string | null;
            contact_email?: string | null;
            provenance?: string | null;
            policy: components["schemas"]["DatasetPolicyView"];
            status: components["schemas"]["DatasetStatus"];
            latest_published_version?: components["schemas"]["DatasetVersionSummary"] | null;
            created_by?: components["schemas"]["Id"];
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        DatasetVersionSummary: {
            dataset_version_id: components["schemas"]["Id"];
            version_label: string;
            status: components["schemas"]["DatasetVersionStatus"];
            /** Format: date-time */
            published_at?: string | null;
            /** @description Latest COMPLETED result of TABULAR_ML_BASIC if present, else GENERIC_BASIC; null if none */
            readiness_overall?: components["schemas"]["ReadinessOverall"] | null;
        };
        DatasetVersion: components["schemas"]["DatasetVersionSummary"] & {
            dataset_id: components["schemas"]["Id"];
            change_note?: string | null;
            files: components["schemas"]["DatasetFile"][];
            file_count: number;
            total_bytes: number;
            /** @description sha256 over sorted 'path\tsize\tsha256' lines; set on publish */
            manifest_sha256?: string | null;
            created_at: components["schemas"]["Timestamp"];
        };
        DatasetFile: {
            file_id: components["schemas"]["Id"];
            /** @description Relative path, no '..' or leading '/' */
            path: string;
            size_bytes: number;
            sha256: string;
            media_type: string;
            status: components["schemas"]["FileStatus"];
        };
        UploadSessionCreate: {
            files: {
                path: string;
                /** @description P0 per-file limit 50 GiB */
                size_bytes: number;
                sha256: string;
                media_type: string;
            }[];
        };
        UploadSession: {
            upload_session_id: components["schemas"]["Id"];
            dataset_version_id: components["schemas"]["Id"];
            /** @enum {string} */
            status: "OPEN" | "COMPLETED" | "EXPIRED";
            expires_at: components["schemas"]["Timestamp"];
            files: {
                file_id: components["schemas"]["Id"];
                path: string;
                status: components["schemas"]["FileStatus"];
                failure_code?: string | null;
                upload: {
                    /** @constant */
                    method: "PUT";
                    /** Format: uri */
                    url: string;
                    headers?: {
                        [key: string]: string;
                    };
                } | {
                    /** @constant */
                    method: "MULTIPART";
                    part_size_bytes: number;
                    parts: {
                        part_number: number;
                        /** Format: uri */
                        url: string;
                    }[];
                };
            }[];
        };
        DatasetSearchHit: {
            dataset_id: components["schemas"]["Id"];
            title: string;
            snippet?: string;
            owner_organization_id: components["schemas"]["Id"];
            owner_organization_name?: string;
            access_level: components["schemas"]["AccessLevel"];
            keywords?: string[];
            allowed_purposes?: components["schemas"]["Purpose"][];
            latest_version_label?: string | null;
            readiness_overall?: components["schemas"]["ReadinessOverall"] | null;
            updated_at?: components["schemas"]["Timestamp"];
        };
        FacetBucket: {
            value: string;
            label?: string;
            count: number;
        };
        DatasetSearchResult: components["schemas"]["PageEnvelope"] & {
            items?: components["schemas"]["DatasetSearchHit"][];
            total: number;
            facets: {
                access_level?: components["schemas"]["FacetBucket"][];
                owner_organization_id?: components["schemas"]["FacetBucket"][];
                purpose?: components["schemas"]["FacetBucket"][];
                keyword?: components["schemas"]["FacetBucket"][];
                readiness_status?: components["schemas"]["FacetBucket"][];
            };
        };
        AccessRequestCreate: {
            dataset_id: components["schemas"]["Id"];
            project_id: components["schemas"]["Id"];
            purpose: components["schemas"]["Purpose"];
            purpose_detail: string;
            operations: components["schemas"]["Operation"][];
            requested_days: number;
        };
        AccessRequest: {
            access_request_id: components["schemas"]["Id"];
            dataset_id: components["schemas"]["Id"];
            dataset_title?: string;
            project_id: components["schemas"]["Id"];
            project_name?: string;
            requester_user_id: components["schemas"]["Id"];
            requester_display_name?: string;
            requester_organization_id: components["schemas"]["Id"];
            owner_organization_id: components["schemas"]["Id"];
            purpose: components["schemas"]["Purpose"];
            purpose_detail: string;
            operations: components["schemas"]["Operation"][];
            requested_days: number;
            status: components["schemas"]["AccessRequestStatus"];
            history?: {
                status: components["schemas"]["AccessRequestStatus"];
                at: components["schemas"]["Timestamp"];
                by_user_id?: components["schemas"]["Id"];
                comment?: string | null;
            }[];
            access_grant_id?: components["schemas"]["Id"] | null;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        AccessApprove: {
            /** @description <= requested_days and <= max_grant_days; expires_at = approved_at + grant_days */
            grant_days: number;
            /** @description Subset of requested operations; default = requested */
            operations?: components["schemas"]["Operation"][];
            note?: string;
        };
        AccessDecisionResult: {
            access_request: components["schemas"]["AccessRequest"];
            access_grant?: components["schemas"]["AccessGrant"] | null;
        };
        AccessGrant: {
            access_grant_id: components["schemas"]["Id"];
            access_request_id?: components["schemas"]["Id"];
            /** @constant */
            subject_type: "USER";
            subject_user_id: components["schemas"]["Id"];
            project_id: components["schemas"]["Id"];
            dataset_id: components["schemas"]["Id"];
            dataset_title?: string;
            purpose: components["schemas"]["Purpose"];
            operations: components["schemas"]["Operation"][];
            valid_from: components["schemas"]["Timestamp"];
            expires_at: components["schemas"]["Timestamp"];
            granted_by: components["schemas"]["Id"];
            /** @example data_access@1.0.0 */
            policy_version: string;
            /** @description Computed: ACTIVE with expires_at <= now is returned as EXPIRED */
            status: components["schemas"]["AccessGrantStatus"];
            /** Format: date-time */
            revoked_at?: string | null;
            revoked_by?: components["schemas"]["Id"] | null;
            revocation_reason?: string | null;
        };
        DownloadSessionCreate: {
            /** @description Required when basis would be GRANT (CONTROLLED/SENSITIVE for non-owner org) */
            project_id?: components["schemas"]["Id"];
            /** @description Default: all files of the version */
            file_ids?: components["schemas"]["Id"][];
        };
        DownloadSession: {
            dataset_version_id: components["schemas"]["Id"];
            /** @enum {string} */
            basis: "PUBLIC" | "OWNER_ORGANIZATION" | "GRANT";
            access_grant_id?: components["schemas"]["Id"] | null;
            /** @description URL expiry (now + 300s) */
            expires_at: components["schemas"]["Timestamp"];
            files: {
                file_id: components["schemas"]["Id"];
                path: string;
                /** Format: uri */
                url: string;
                size_bytes: number;
                sha256: string;
            }[];
        };
        ReadinessProfile: {
            profile_id: string;
            version: string;
            name: string;
            description?: string;
            checks: {
                check_id: string;
                /**
                 * @description REQUIRED FAIL => overall FAIL; RECOMMENDED FAIL => overall WARNING
                 * @enum {string}
                 */
                severity: "REQUIRED" | "RECOMMENDED";
            }[];
        };
        ReadinessCheckResult: {
            check_id: string;
            status: components["schemas"]["ReadinessCheckStatus"];
            /** @enum {string} */
            severity: "REQUIRED" | "RECOMMENDED";
            message: string;
            /** @description Statistics/locations only, never raw values (D-018) */
            evidence: {
                [key: string]: unknown;
            };
        };
        ReadinessValidation: {
            validation_id: components["schemas"]["Id"];
            dataset_version_id: components["schemas"]["Id"];
            profile_id: string;
            profile_version: string;
            run_status: components["schemas"]["ReadinessRunStatus"];
            overall_status?: components["schemas"]["ReadinessOverall"] | null;
            summary?: {
                pass?: number;
                warning?: number;
                fail?: number;
                not_applicable?: number;
            };
            checks?: components["schemas"]["ReadinessCheckResult"][];
            validator_version?: string;
            /** @description sha256(manifest_sha256 + metadata_snapshot_sha256 + profile_id + profile_version + validator_version) */
            input_fingerprint?: string;
            /** @description Set when run_status=FAILED */
            error?: string | null;
            /** @enum {string} */
            triggered_by?: "AUTO_ON_PUBLISH" | "USER";
            created_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
        };
        AuditEvent: {
            audit_event_id: components["schemas"]["Id"];
            occurred_at: components["schemas"]["Timestamp"];
            action: components["schemas"]["AuditAction"];
            /** @enum {string} */
            result: "SUCCESS" | "DENIED";
            reason?: string | null;
            actor: {
                /** @enum {string} */
                type: "USER" | "SYSTEM";
                user_id?: components["schemas"]["Id"] | null;
                display_name?: string | null;
                organization_id?: components["schemas"]["Id"] | null;
            };
            resource: {
                type: components["schemas"]["ResourceType"];
                id: components["schemas"]["Id"];
                owner_organization_id?: components["schemas"]["Id"] | null;
            };
            project_id?: components["schemas"]["Id"] | null;
            policy_version?: string | null;
            source_event_id: components["schemas"]["Id"];
            source_event_type?: string;
            /** @description = source event correlation_id */
            trace_id: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Notification: {
            notification_id: components["schemas"]["Id"];
            type: components["schemas"]["NotificationType"];
            title: string;
            body?: string;
            /** @description Web route, e.g. /commons/access/{id} */
            link?: string;
            read: boolean;
            created_at: components["schemas"]["Timestamp"];
        };
    };
    responses: {
        /** @description Error envelope. See contracts/error_codes.json for codes and HTTP mapping. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
        OrganizationId: components["schemas"]["Id"];
        UserId: components["schemas"]["Id"];
        ProjectId: components["schemas"]["Id"];
        DatasetId: components["schemas"]["Id"];
        VersionId: components["schemas"]["Id"];
        AccessRequestId: components["schemas"]["Id"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description A dependency is down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            /** @description JIT provisioning email conflict (CONFLICT) */
            409: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Matches display_name or email prefix */
                q?: string;
                organization_id?: components["schemas"]["Id"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["IdentityPublicProfile"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["OrganizationSummary"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listOrganizationMembers: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                organization_id: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["OrganizationMembership"][];
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateOrganizationMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: components["parameters"]["OrganizationId"];
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    roles?: components["schemas"]["OrgRole"][];
                    status?: components["schemas"]["ActiveStatus"];
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMembership"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                scope?: "mine" | "discover";
                status?: components["schemas"]["ProjectStatus"];
                q?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["ProjectSummary"][];
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    archiveProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listProjectMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ProjectMember"][];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    addProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_id: components["schemas"]["Id"];
                    role: components["schemas"]["ProjectRole"];
                };
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMember"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    removeProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateProjectMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role: components["schemas"]["ProjectRole"];
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMember"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    searchDatasets: {
        parameters: {
            query?: {
                q?: string;
                access_level?: components["schemas"]["AccessLevel"][];
                owner_organization_id?: components["schemas"]["Id"][];
                purpose?: components["schemas"]["Purpose"][];
                keyword?: string[];
                readiness_status?: components["schemas"]["ReadinessOverall"][];
                sort?: "relevance" | "updated_desc" | "title_asc";
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSearchResult"];
                };
            };
        };
    };
    createDataset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getDataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: components["parameters"]["DatasetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dataset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateDataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: components["parameters"]["DatasetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getDatasetPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: components["parameters"]["DatasetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetPolicyView"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listDatasetVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: components["parameters"]["DatasetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["DatasetVersion"][];
                    };
                };
            };
        };
    };
    createDatasetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: components["parameters"]["DatasetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example v1
                     * @example 2026.09
                     */
                    version_label: string;
                    change_note?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetVersion"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getDatasetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetVersion"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    createUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSessionCreate"];
            };
        };
        responses: {
            /** @description Session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSession"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_session_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSession"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteDraftFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
                file_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    completeUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_session_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Required for multipart files. */
                    parts?: {
                        file_id: components["schemas"]["Id"];
                        etags: {
                            part_number: number;
                            etag: string;
                        }[];
                    }[];
                };
            };
        };
        responses: {
            /** @description Session result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSession"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    publishDatasetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetVersion"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listAccessRequests: {
        parameters: {
            query?: {
                /** @description requester = my requests; reviewer = requests for datasets owned by orgs where I am DATA_STEWARD */
                role?: "requester" | "reviewer";
                status?: components["schemas"]["AccessRequestStatus"][];
                project_id?: components["schemas"]["Id"];
                dataset_id?: components["schemas"]["Id"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["AccessRequest"][];
                    };
                };
            };
        };
    };
    createAccessRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessRequestCreate"];
            };
        };
        responses: {
            /** @description Submitted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequest"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getAccessRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequest"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    startAccessReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Under review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequest"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    approveAccessRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessApprove"];
            };
        };
        responses: {
            /** @description Approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessDecisionResult"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    rejectAccessRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessDecisionResult"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    requestAccessChanges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    comment: string;
                };
            };
        };
        responses: {
            /** @description Changes requested */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessDecisionResult"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    resubmitAccessRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    purpose?: components["schemas"]["Purpose"];
                    purpose_detail?: string;
                    operations?: components["schemas"]["Operation"][];
                    requested_days?: number;
                };
            };
        };
        responses: {
            /** @description Resubmitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequest"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    withdrawAccessRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_request_id: components["parameters"]["AccessRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawn */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequest"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listAccessGrants: {
        parameters: {
            query?: {
                /** @description subject = grants I hold; owner = grants on my org's datasets (DATA_STEWARD/ORG_ADMIN) */
                role?: "subject" | "owner";
                status?: components["schemas"]["AccessGrantStatus"][];
                project_id?: components["schemas"]["Id"];
                dataset_id?: components["schemas"]["Id"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["AccessGrant"][];
                    };
                };
            };
        };
    };
    revokeAccessGrant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_grant_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessGrant"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    createDownloadSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadSessionCreate"];
            };
        };
        responses: {
            /** @description Signed URLs */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadSession"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listReadinessProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ReadinessProfile"][];
                    };
                };
            };
        };
    };
    startReadinessValidation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example GENERIC_BASIC
                     * @example TABULAR_ML_BASIC
                     */
                    profile_id: string;
                };
            };
        };
        responses: {
            /** @description Existing identical result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessValidation"];
                };
            };
            /** @description Queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessValidation"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getReadiness: {
        parameters: {
            query?: {
                profile_id?: string;
            };
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ReadinessValidation"][];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                action?: components["schemas"]["AuditAction"][];
                actor_user_id?: components["schemas"]["Id"];
                organization_id?: components["schemas"]["Id"];
                project_id?: components["schemas"]["Id"];
                resource_type?: components["schemas"]["ResourceType"];
                resource_id?: components["schemas"]["Id"];
                from?: string;
                to?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events (newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["AuditEvent"][];
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                unread_only?: boolean;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller's notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["Notification"][];
                        unread_count?: number;
                    };
                };
            };
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All marked read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
