import type { MetadataRoute } from "next";
import { SITE_NAME } from "@/shared/config";

/**
 * Web app manifest (/manifest.webmanifest). Colours are the light theme's page background (--color-bg); the icons are
 * generated by scripts/brand-assets.mjs into public/icons. The maskable icon is full bleed with the mark inside the
 * 80% safe zone, so launchers can crop it to any shape.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${SITE_NAME} · NAIS 국가과학AI연구센터`,
    short_name: SITE_NAME,
    description: "NAIS 국가과학AI연구센터의 연구 데이터 포털",
    lang: "ko",
    start_url: "/commons",
    scope: "/",
    display: "standalone",
    theme_color: "#fcfcfd",
    background_color: "#fcfcfd",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
      { src: "/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
    ],
  };
}
