"""Starter controlled vocabulary (Wave 1.5 spec §3.1). Imported by migration catalog_0002; never edited in place —
add terms with createVocabularyTerm. IRIs are left NULL on purpose: mapping to EMMO/QUDT/etc. is curation."""

SEED_TERMS: tuple[tuple[str, str, str, str, str | None], ...] = (
    # (scheme, code, label_ko, label_en, parent_code)
    ("SUBJECT", "MATERIALS", "재료", "Materials", None),
    ("SUBJECT", "ENERGY", "에너지", "Energy", None),
    ("SUBJECT", "CHEMISTRY", "화학", "Chemistry", None),
    ("SUBJECT", "MECHANICAL", "기계", "Mechanical engineering", None),
    ("SUBJECT", "ELECTRONICS_ICT", "전자·정보통신", "Electronics and ICT", None),
    ("SUBJECT", "BIO_HEALTH", "생명·보건의료", "Life sciences and health", None),
    ("SUBJECT", "NUCLEAR", "원자력", "Nuclear", None),
    ("SUBJECT", "FUSION", "핵융합", "Fusion", None),
    ("SUBJECT", "AEROSPACE", "항공우주", "Aerospace", None),
    ("SUBJECT", "OCEAN", "해양", "Ocean", None),
    ("SUBJECT", "GEOSCIENCE", "지질자원", "Geoscience and resources", None),
    ("SUBJECT", "CONSTRUCTION", "건설", "Construction", None),
    ("SUBJECT", "RAILWAY", "철도", "Railway", None),
    ("SUBJECT", "FOOD", "식품", "Food", None),
    ("SUBJECT", "KOREAN_MEDICINE", "한의학", "Korean medicine", None),
    ("SUBJECT", "ASTRONOMY", "천문", "Astronomy", None),
    ("SUBJECT", "STANDARDS", "표준·측정", "Standards and metrology", None),
    ("SUBJECT", "ENVIRONMENT", "환경", "Environment", None),
    ("SUBJECT", "AI_DATA", "AI·데이터", "AI and data", None),
    ("SUBJECT", "BATTERY", "이차전지", "Batteries", "ENERGY"),
    ("METHOD", "XRD", "X선 회절(XRD)", "X-ray diffraction", None),
    ("METHOD", "SEM", "주사전자현미경(SEM)", "Scanning electron microscopy", None),
    ("METHOD", "TEM", "투과전자현미경(TEM)", "Transmission electron microscopy", None),
    ("METHOD", "XPS", "X선 광전자 분광(XPS)", "X-ray photoelectron spectroscopy", None),
    ("METHOD", "FTIR", "적외선 분광(FTIR)", "Infrared spectroscopy", None),
    ("METHOD", "RAMAN", "라만 분광", "Raman spectroscopy", None),
    ("METHOD", "NMR", "핵자기공명(NMR)", "Nuclear magnetic resonance", None),
    ("METHOD", "MASS_SPEC", "질량분석", "Mass spectrometry", None),
    ("METHOD", "CHROMATOGRAPHY", "크로마토그래피", "Chromatography", None),
    ("METHOD", "ELECTROCHEM_CYCLING", "전기화학 충방전 시험", "Electrochemical cycling", None),
    ("METHOD", "SENSOR_LOGGING", "센서 자동 계측", "Sensor logging", None),
    ("METHOD", "SIMULATION_DFT", "제일원리 계산(DFT)", "DFT simulation", None),
    ("METHOD", "SIMULATION_MD", "분자동역학 계산", "Molecular dynamics simulation", None),
    ("METHOD", "OPTICAL_IMAGING", "광학 영상", "Optical imaging", None),
    ("METHOD", "SURVEY", "설문·조사", "Survey", None),
    ("MATERIAL", "CATHODE", "양극재", "Cathode material", None),
    ("MATERIAL", "ANODE", "음극재", "Anode material", None),
    ("MATERIAL", "ELECTROLYTE", "전해질", "Electrolyte", None),
    ("MATERIAL", "POLYMER", "고분자", "Polymer", None),
    ("MATERIAL", "POLYMER_MEMBRANE", "고분자 막", "Polymer membrane", "POLYMER"),
    ("MATERIAL", "METAL_ALLOY", "금속·합금", "Metal and alloy", None),
    ("MATERIAL", "STEEL", "철강", "Steel", "METAL_ALLOY"),
    ("MATERIAL", "CERAMIC", "세라믹", "Ceramic", None),
    ("MATERIAL", "SEMICONDUCTOR", "반도체", "Semiconductor", None),
    ("MATERIAL", "CATALYST", "촉매", "Catalyst", None),
    ("MATERIAL", "COMPOSITE", "복합재", "Composite", None),
    ("MATERIAL", "NANOMATERIAL", "나노소재", "Nanomaterial", None),
    ("MATERIAL", "TWO_D_MATERIAL", "2차원 소재", "2D material", "NANOMATERIAL"),
    ("MATERIAL", "CONCRETE", "콘크리트", "Concrete", None),
    ("MATERIAL", "BIOMATERIAL", "바이오소재", "Biomaterial", None),
    ("MATERIAL", "PROTEIN", "단백질", "Protein", None),
    ("MATERIAL", "CELL_LINE", "세포주", "Cell line", None),
    ("MATERIAL", "SOIL", "토양", "Soil", None),
    ("MATERIAL", "SEAWATER", "해수", "Seawater", None),
    ("MATERIAL", "ATMOSPHERE", "대기", "Atmosphere", None),
)
