# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum, StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class Id(RootModel[UUID]):
    root: UUID


class Timestamp(RootModel[AwareDatetime]):
    root: AwareDatetime


class Error(BaseModel):
    code: str = Field(..., examples=['ACCESS_GRANT_EXPIRED'])
    message: str
    trace_id: str
    details: dict[str, Any] | None = None


class ErrorEnvelope(BaseModel):
    error: Error


class Page(BaseModel):
    next_cursor: str | None = None
    has_more: bool


class PageEnvelope(BaseModel):
    items: list[Any]
    page: Page


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    down = 'down'


class Checks(StrEnum):
    ok = 'ok'
    down = 'down'


class Health(BaseModel):
    status: Status
    checks: dict[str, Checks] | None = None


class ActiveStatus(StrEnum):
    ACTIVE = 'ACTIVE'
    DISABLED = 'DISABLED'


class OrganizationType(StrEnum):
    RESEARCH_INSTITUTE = 'RESEARCH_INSTITUTE'
    UNIVERSITY = 'UNIVERSITY'
    COMPANY = 'COMPANY'
    PLATFORM_OPERATOR = 'PLATFORM_OPERATOR'


class OrgRole(StrEnum):
    ORG_ADMIN = 'ORG_ADMIN'
    DATA_STEWARD = 'DATA_STEWARD'
    RESOURCE_MANAGER = 'RESOURCE_MANAGER'


class PlatformRole(StrEnum):
    PLATFORM_ADMIN = 'PLATFORM_ADMIN'


class ProjectRole(StrEnum):
    PROJECT_OWNER = 'PROJECT_OWNER'
    PROJECT_ADMIN = 'PROJECT_ADMIN'
    RESEARCHER = 'RESEARCHER'
    VIEWER = 'VIEWER'


class ProjectStatus(StrEnum):
    ACTIVE = 'ACTIVE'
    ARCHIVED = 'ARCHIVED'


class ProjectVisibility(StrEnum):
    PRIVATE = 'PRIVATE'
    PUBLIC = 'PUBLIC'


class AccessLevel(StrEnum):
    PUBLIC = 'PUBLIC'
    INTERNAL = 'INTERNAL'
    CONTROLLED = 'CONTROLLED'
    SENSITIVE = 'SENSITIVE'


class Purpose(StrEnum):
    ACADEMIC_RESEARCH = 'ACADEMIC_RESEARCH'
    AI_TRAINING = 'AI_TRAINING'
    COMMERCIAL_RESEARCH = 'COMMERCIAL_RESEARCH'
    EDUCATION = 'EDUCATION'
    PUBLIC_INTEREST = 'PUBLIC_INTEREST'


class Operation(StrEnum):
    READ = 'READ'
    COMPUTE = 'COMPUTE'
    WRITE = 'WRITE'


class DatasetStatus(StrEnum):
    ACTIVE = 'ACTIVE'
    WITHDRAWN = 'WITHDRAWN'


class DatasetVersionStatus(StrEnum):
    DRAFT = 'DRAFT'
    PUBLISHED = 'PUBLISHED'
    WITHDRAWN = 'WITHDRAWN'


class FileStatus(StrEnum):
    PENDING = 'PENDING'
    UPLOADED = 'UPLOADED'
    VERIFIED = 'VERIFIED'
    FAILED = 'FAILED'


class AccessRequestStatus(StrEnum):
    DRAFT = 'DRAFT'
    SUBMITTED = 'SUBMITTED'
    UNDER_REVIEW = 'UNDER_REVIEW'
    CHANGE_REQUESTED = 'CHANGE_REQUESTED'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    WITHDRAWN = 'WITHDRAWN'


class AccessGrantStatus(StrEnum):
    ACTIVE = 'ACTIVE'
    EXPIRED = 'EXPIRED'
    REVOKED = 'REVOKED'


class ReadinessRunStatus(StrEnum):
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'


class ReadinessOverall(StrEnum):
    PASS = 'PASS'
    WARNING = 'WARNING'
    FAIL = 'FAIL'


class ReadinessCheckStatus(StrEnum):
    PASS = 'PASS'
    WARNING = 'WARNING'
    FAIL = 'FAIL'
    NOT_APPLICABLE = 'NOT_APPLICABLE'


class ResourceType(StrEnum):
    USER = 'USER'
    ORGANIZATION = 'ORGANIZATION'
    MEMBERSHIP = 'MEMBERSHIP'
    PROJECT = 'PROJECT'
    PROJECT_MEMBER = 'PROJECT_MEMBER'
    DATASET = 'DATASET'
    DATASET_VERSION = 'DATASET_VERSION'
    DATASET_FILE = 'DATASET_FILE'
    ACCESS_REQUEST = 'ACCESS_REQUEST'
    ACCESS_GRANT = 'ACCESS_GRANT'
    READINESS_VALIDATION = 'READINESS_VALIDATION'
    PROJECT_INPUT = 'PROJECT_INPUT'
    RECIPE = 'RECIPE'
    RUN = 'RUN'
    OUTPUT = 'OUTPUT'
    PUBLISH_REQUEST = 'PUBLISH_REQUEST'
    THREAD = 'THREAD'
    RESEARCH_NOTE = 'RESEARCH_NOTE'


class AuditAction(StrEnum):
    LOGIN = 'LOGIN'
    USER_CREATED = 'USER_CREATED'
    ORGANIZATION_CREATED = 'ORGANIZATION_CREATED'
    ADMIN_ROLE_CHANGED = 'ADMIN_ROLE_CHANGED'
    PROJECT_CREATED = 'PROJECT_CREATED'
    PROJECT_ARCHIVED = 'PROJECT_ARCHIVED'
    PROJECT_MEMBER_ADDED = 'PROJECT_MEMBER_ADDED'
    PROJECT_MEMBER_REMOVED = 'PROJECT_MEMBER_REMOVED'
    PROJECT_MEMBER_ROLE_CHANGED = 'PROJECT_MEMBER_ROLE_CHANGED'
    DATASET_CREATED = 'DATASET_CREATED'
    DATASET_VERSION_PUBLISHED = 'DATASET_VERSION_PUBLISHED'
    DATASET_UPDATED = 'DATASET_UPDATED'
    POLICY_CHANGED = 'POLICY_CHANGED'
    ACCESS_REQUESTED = 'ACCESS_REQUESTED'
    ACCESS_REVIEW_STARTED = 'ACCESS_REVIEW_STARTED'
    ACCESS_APPROVED = 'ACCESS_APPROVED'
    ACCESS_REJECTED = 'ACCESS_REJECTED'
    ACCESS_CHANGES_REQUESTED = 'ACCESS_CHANGES_REQUESTED'
    ACCESS_WITHDRAWN = 'ACCESS_WITHDRAWN'
    ACCESS_REVOKED = 'ACCESS_REVOKED'
    ACCESS_EXPIRED = 'ACCESS_EXPIRED'
    FILE_DOWNLOADED = 'FILE_DOWNLOADED'
    DOWNLOAD_DENIED = 'DOWNLOAD_DENIED'
    READINESS_VALIDATION_COMPLETED = 'READINESS_VALIDATION_COMPLETED'
    PROJECT_INPUT_ADDED = 'PROJECT_INPUT_ADDED'
    PROJECT_INPUT_VERSION_CHANGED = 'PROJECT_INPUT_VERSION_CHANGED'
    PROJECT_INPUT_REMOVED = 'PROJECT_INPUT_REMOVED'
    RECIPE_SAVED = 'RECIPE_SAVED'
    RUN_SUCCEEDED = 'RUN_SUCCEEDED'
    RUN_FAILED = 'RUN_FAILED'
    OUTPUT_CREATED = 'OUTPUT_CREATED'
    OUTPUT_PUBLISH_REQUESTED = 'OUTPUT_PUBLISH_REQUESTED'
    OUTPUT_PUBLISH_DECIDED = 'OUTPUT_PUBLISH_DECIDED'
    COMMENT_ADDED = 'COMMENT_ADDED'
    NOTE_SUBMITTED = 'NOTE_SUBMITTED'
    NOTE_SIGNED = 'NOTE_SIGNED'
    NOTE_REJECTED = 'NOTE_REJECTED'
    NOTE_VIEWED = 'NOTE_VIEWED'


class NotificationType(StrEnum):
    PROJECT_INVITATION = 'PROJECT_INVITATION'
    ACCESS_SUBMITTED = 'ACCESS_SUBMITTED'
    ACCESS_APPROVED = 'ACCESS_APPROVED'
    ACCESS_REJECTED = 'ACCESS_REJECTED'
    ACCESS_CHANGES_REQUESTED = 'ACCESS_CHANGES_REQUESTED'
    ACCESS_EXPIRING = 'ACCESS_EXPIRING'
    ACCESS_REVOKED = 'ACCESS_REVOKED'
    DATASET_PUBLISHED = 'DATASET_PUBLISHED'
    OUTPUT_PUBLISH_REQUESTED = 'OUTPUT_PUBLISH_REQUESTED'
    OUTPUT_PUBLISH_DECIDED = 'OUTPUT_PUBLISH_DECIDED'
    NOTE_SUBMITTED = 'NOTE_SUBMITTED'
    NOTE_REJECTED = 'NOTE_REJECTED'
    NOTE_SIGNED = 'NOTE_SIGNED'
    DATASET_COMMENT_ADDED = 'DATASET_COMMENT_ADDED'
    RUN_FAILED = 'RUN_FAILED'


class IdentityPublicProfile(BaseModel):
    user_id: Id
    display_name: str
    organization_id: Id
    organization_name: str | None = None
    status: ActiveStatus
    national_researcher_number: constr(pattern=r'^[0-9]{8}$') | None = None


class OrganizationSummary(BaseModel):
    organization_id: Id
    code: constr(pattern=r'^[a-z0-9-]{2,32}$') = Field(..., examples=['inst-a'])
    name: str
    type: OrganizationType


class Organization(OrganizationSummary):
    ror_id: str | None = Field(None, description='P2 extension')
    homepage_url: AnyUrl | None = None
    member_count: int | None = None
    dataset_count: int | None = None
    created_at: Timestamp | None = None


class OrganizationMembership(BaseModel):
    user_id: Id
    organization_id: Id
    display_name: str | None = None
    email: EmailStr | None = None
    roles: list[OrgRole]
    status: ActiveStatus
    updated_at: Timestamp | None = None
    started_at: Timestamp | None = None


class Me(BaseModel):
    user_id: Id
    display_name: str
    email: EmailStr
    status: ActiveStatus
    organization: OrganizationSummary
    org_roles: list[OrgRole]
    platform_roles: list[PlatformRole]
    national_researcher_number: constr(pattern=r'^[0-9]{8}$') | None = None


class MeUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    national_researcher_number: constr(pattern=r'^[0-9]{8}$') | None = Field(
        None, description='NTIS 국가연구자번호; null clears'
    )


class UserTransfer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    organization_id: Id
    roles: list[OrgRole] | None = []


class ProjectSummary(BaseModel):
    project_id: Id
    name: str
    status: ProjectStatus
    visibility: ProjectVisibility
    lead_organization_id: Id
    my_role: ProjectRole | None = None
    lead_organization_name: str | None = None
    member_count: int | None = None
    updated_at: Timestamp | None = None


class Role(StrEnum):
    LEAD = 'LEAD'
    PARTNER = 'PARTNER'


class Organization1(BaseModel):
    organization_id: Id
    name: str | None = None
    role: Role = Field(
        ..., description="PARTNER rows are derived from members' organizations"
    )


class Project(ProjectSummary):
    description: str
    keywords: list[str] | None = None
    start_date: date_aliased | None = None
    end_date: date_aliased | None = None
    organizations: list[Organization1]
    created_by: Id | None = None
    created_at: Timestamp
    archived_at: AwareDatetime | None = None


class Keyword(RootModel[constr(max_length=50)]):
    root: constr(max_length=50)


class ProjectCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=2, max_length=200)
    description: constr(max_length=10000)
    visibility: ProjectVisibility | None = None
    keywords: list[Keyword] | None = Field(None, max_length=20)
    start_date: date_aliased | None = None
    end_date: date_aliased | None = None


class ProjectUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=2, max_length=200) | None = None
    description: constr(max_length=10000) | None = None
    visibility: ProjectVisibility | None = None
    keywords: list[Keyword] | None = Field(None, max_length=20)
    start_date: date_aliased | None = None
    end_date: date_aliased | None = None


class ProjectMember(BaseModel):
    project_id: Id
    user_id: Id
    display_name: str | None = None
    organization_id: Id
    organization_name: str | None = None
    role: ProjectRole
    joined_at: Timestamp
    added_by: Id | None = None


class DatasetPolicyView(BaseModel):
    dataset_id: Id
    owner_organization_id: Id
    access_level: AccessLevel
    allowed_purposes: list[Purpose] = Field(..., min_length=1)
    approval_required: bool = Field(
        ...,
        description='P0: always true for CONTROLLED/SENSITIVE; ignored for PUBLIC/INTERNAL',
    )
    max_grant_days: conint(ge=1, le=365) = Field(..., description='SENSITIVE <= 30')


class VocabularyScheme(StrEnum):
    SUBJECT = 'SUBJECT'
    METHOD = 'METHOD'
    MATERIAL = 'MATERIAL'


class UpdateFrequency(StrEnum):
    ONCE = 'ONCE'
    MONTHLY = 'MONTHLY'
    QUARTERLY = 'QUARTERLY'
    YEARLY = 'YEARLY'
    IRREGULAR = 'IRREGULAR'


class ContributorRole(StrEnum):
    CO_INVESTIGATOR = 'CO_INVESTIGATOR'
    DATA_COLLECTOR = 'DATA_COLLECTOR'
    DATA_CURATOR = 'DATA_CURATOR'


class VocabularyTerm(BaseModel):
    scheme: VocabularyScheme
    code: constr(pattern=r'^[A-Z0-9_]{2,64}$')
    label_ko: str
    label_en: str
    iri: constr(pattern=r'^https?://\S+$') | None = None
    parent_code: str | None = None


class VocabularyTermCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(pattern=r'^[A-Z0-9_]{2,64}$')
    label_ko: constr(min_length=1, max_length=200)
    label_en: constr(min_length=1, max_length=200)
    iri: constr(pattern=r'^https?://\S+$') | None = None
    parent_code: constr(pattern=r'^[A-Z0-9_]{2,64}$') | None = None


class OrganizationRef(BaseModel):
    organization_id: Id | None = Field(
        ..., description='null for an organization outside the council (free-text name)'
    )
    name: str


class DatasetPerson(BaseModel):
    user_id: Id
    display_name: str
    national_researcher_number: str | None = None
    status: ActiveStatus
    affiliation: OrganizationRef = Field(
        ..., description='Organization at the time the person was assigned (당시 소속)'
    )
    current_organization: OrganizationRef | None = Field(
        None, description='Current organization (null if unknown)'
    )
    email: EmailStr | None = Field(
        None,
        description='Only on people.steward_contact and only when contact_email_public',
    )


class DatasetContributor(DatasetPerson):
    role: ContributorRole


class Contributor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_id: Id
    role: ContributorRole


class DatasetContributorsPut(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contributors: list[Contributor] = Field(..., max_length=50)


class DatasetPeople(BaseModel):
    principal_investigator: DatasetPerson | None
    steward_contact: DatasetPerson | None
    contributors: list[DatasetContributor]
    steward_contact_absent: bool = Field(
        ...,
        description='Steward contact unset, disabled, or no longer a member of the owner organization (담당자 재지정 필요)',
    )


class RelatedPublication(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: constr(min_length=1, max_length=300)
    doi: constr(pattern=r'^10\.\d{4,9}/\S+$') | None = None
    url: constr(pattern=r'^https?://\S+$') | None = None


class DatasetJsonLd(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    field_context: dict[str, Any] = Field(..., alias='@context')
    field_type: list[str] = Field(..., alias='@type')
    field_id: AnyUrl = Field(..., alias='@id')
    name: str


class FilePreviewStatus(StrEnum):
    PENDING = 'PENDING'
    READY = 'READY'
    FAILED = 'FAILED'
    UNSUPPORTED = 'UNSUPPORTED'


class Type(StrEnum):
    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    date = 'date'
    datetime = 'datetime'


class ColumnProfile(BaseModel):
    name: str
    type: Type = Field(
        ..., description='Declared in _schema.json, else inferred from the sample'
    )
    unit: str | None = None
    description: str | None = None
    concept_iri: str | None = None
    missing_ratio: confloat(ge=0.0, le=1.0)
    distinct_count: conint(ge=0)
    distinct_capped: bool | None = Field(
        None,
        description='true when distinct values exceeded the 1,000 counting cap (distinct_count is then a lower bound)',
    )


class FailureCode(Enum):
    UNPARSEABLE = 'UNPARSEABLE'
    TIMEOUT = 'TIMEOUT'
    GENERATION_FAILED = 'GENERATION_FAILED'
    NoneType_None = None


class Format(StrEnum):
    csv = 'csv'
    tsv = 'tsv'
    parquet = 'parquet'


class FileProfile(BaseModel):
    file_id: Id
    path: str
    status: FilePreviewStatus
    failure_code: FailureCode | None = None
    generated_at: AwareDatetime | None = None
    format: Format | None = None
    rows_sampled: int | None = None
    total_rows: int | None = Field(
        None,
        description='Exact row count when known (parquet metadata, or a CSV/TSV read to the end)',
    )
    truncated: bool | None = Field(
        None, description='Sample stopped at the row/byte limit'
    )
    columns_truncated: bool | None = None
    columns: list[ColumnProfile]


class Kind(StrEnum):
    numeric = 'numeric'
    categorical = 'categorical'
    other = 'other'


class HistogramItem(BaseModel):
    lower: float
    upper: float
    count: int


class TopValue(BaseModel):
    value: str
    count: int


class ColumnDistribution(BaseModel):
    name: str
    kind: Kind
    min: float | None = None
    max: float | None = None
    mean: float | None = None
    histogram: list[HistogramItem] | None = None
    top_values: list[TopValue] | None = None


class FilePreview(BaseModel):
    file_id: Id
    status: FilePreviewStatus
    header: list[str]
    rows: list[list[constr(max_length=200) | None]] = Field(..., max_length=100)
    rows_truncated: bool
    columns: list[ColumnDistribution]


class SubjectCode(RootModel[constr(pattern=r'^[A-Z0-9_]{2,64}$')]):
    root: constr(pattern=r'^[A-Z0-9_]{2,64}$')


class MethodCode(RootModel[constr(pattern=r'^[A-Z0-9_]{2,64}$')]):
    root: constr(pattern=r'^[A-Z0-9_]{2,64}$')


class MaterialCode(RootModel[constr(pattern=r'^[A-Z0-9_]{2,64}$')]):
    root: constr(pattern=r'^[A-Z0-9_]{2,64}$')


class DatasetCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    owner_organization_id: Id
    title: constr(min_length=3, max_length=300)
    description: constr(max_length=20000)
    keywords: list[Keyword] | None = Field(None, max_length=30)
    domain: str | None = Field(None, examples=['materials', 'bio', 'energy'])
    access_level: AccessLevel
    license: str = Field(..., examples=['CC-BY-4.0', 'NAIS-CONTROLLED-1.0'])
    usage_policy: constr(max_length=10000) | None = None
    allowed_purposes: list[Purpose] = Field(..., min_length=1)
    max_grant_days: conint(ge=1, le=365) | None = 180
    contact_email: EmailStr | None = None
    provenance: constr(max_length=10000) | None = Field(
        None, description='How the data was produced (instrument, method, source)'
    )
    subtitle: constr(max_length=160) | None = Field(
        None, description='One-line summary shown under the title (Data Card)'
    )
    principal_investigator_id: Id
    data_steward_contact_id: Id
    contact_email_public: bool | None = False
    project_title: constr(max_length=300) | None = None
    project_code: constr(max_length=64) | None = None
    funding_agency: constr(max_length=200) | None = None
    subject_codes: list[SubjectCode] | None = Field(None, max_length=5)
    method_codes: list[MethodCode] | None = Field(None, max_length=10)
    material_codes: list[MaterialCode] | None = Field(None, max_length=20)
    method_detail: constr(max_length=4000) | None = None
    temporal_start: date_aliased | None = None
    temporal_end: date_aliased | None = None
    collecting_organization_id: Id | None = None
    collecting_organization_name: constr(min_length=1, max_length=200) | None = None
    update_frequency: UpdateFrequency | None = None
    related_publications: list[RelatedPublication] | None = Field(None, max_length=20)


class DatasetUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: constr(min_length=3, max_length=300) | None = None
    description: constr(max_length=20000) | None = None
    keywords: list[Keyword] | None = Field(None, max_length=30)
    domain: str | None = None
    access_level: AccessLevel | None = None
    license: str | None = None
    usage_policy: constr(max_length=10000) | None = None
    allowed_purposes: list[Purpose] | None = Field(None, min_length=1)
    max_grant_days: conint(ge=1, le=365) | None = None
    contact_email: EmailStr | None = None
    provenance: constr(max_length=10000) | None = None
    status: DatasetStatus | None = None
    subtitle: constr(max_length=160) | None = None
    principal_investigator_id: Id | None = None
    data_steward_contact_id: Id | None = None
    contact_email_public: bool | None = None
    project_title: constr(max_length=300) | None = None
    project_code: constr(max_length=64) | None = None
    funding_agency: constr(max_length=200) | None = None
    subject_codes: list[SubjectCode] | None = Field(None, max_length=5)
    method_codes: list[MethodCode] | None = Field(None, max_length=10)
    material_codes: list[MaterialCode] | None = Field(None, max_length=20)
    method_detail: constr(max_length=4000) | None = None
    temporal_start: date_aliased | None = None
    temporal_end: date_aliased | None = None
    collecting_organization_id: Id | None = None
    collecting_organization_name: constr(min_length=1, max_length=200) | None = None
    update_frequency: UpdateFrequency | None = None
    related_publications: list[RelatedPublication] | None = Field(None, max_length=20)


class Stats(BaseModel):
    file_count: int | None = None
    total_bytes: int | None = None
    media_types: list[str] | None = None


class DatasetVersionSummary(BaseModel):
    dataset_version_id: Id
    version_label: str
    status: DatasetVersionStatus
    published_at: AwareDatetime | None = None
    readiness_overall: ReadinessOverall | None = Field(
        None,
        description='Latest COMPLETED result of TABULAR_ML_BASIC if present, else GENERIC_BASIC; null if none',
    )


class DatasetFile(BaseModel):
    file_id: Id
    path: constr(pattern=r'^[A-Za-z0-9._/-]{1,512}$') = Field(
        ..., description="Relative path, no '..' or leading '/'"
    )
    size_bytes: conint(ge=1)
    sha256: constr(pattern=r'^[a-f0-9]{64}$')
    media_type: str
    status: FileStatus
    inherited: bool | None = Field(
        None,
        description='Inherited from the base/source version without re-upload (same stored object)',
    )


class DatasetVersionUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    change_note: constr(min_length=3, max_length=2000)


class RebaseResolution(StrEnum):
    MINE = 'MINE'
    THEIRS = 'THEIRS'


class RebaseRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    resolutions: dict[str, RebaseResolution] | None = Field(
        None,
        description='path -> MINE | THEIRS for conflicting paths',
        max_length=10000,
    )


class ChangeSummary(BaseModel):
    added: conint(ge=0)
    removed: conint(ge=0)
    changed: conint(ge=0)
    unchanged: conint(ge=0)


class FileChangeStatus(StrEnum):
    ADDED = 'ADDED'
    REMOVED = 'REMOVED'
    CHANGED = 'CHANGED'
    UNCHANGED = 'UNCHANGED'


class FileSide(BaseModel):
    size_bytes: int
    sha256: constr(pattern=r'^[a-f0-9]{64}$')


class FileChange(BaseModel):
    path: str
    status: FileChangeStatus
    before: FileSide | None
    after: FileSide | None
    size_delta: int


class ColumnChange(BaseModel):
    name: str
    type: list[str | None] | None = Field(..., max_length=2, min_length=2)
    unit: list[str | None] | None = Field(..., max_length=2, min_length=2)
    missing_ratio: list[float] | None = Field(..., max_length=2, min_length=2)


class Status1(StrEnum):
    COMPARED = 'COMPARED'
    PROFILE_MISSING = 'PROFILE_MISSING'


class SchemaChange(BaseModel):
    path: str
    status: Status1
    rows: list[int | None] | None = Field(None, max_length=2, min_length=2)
    columns_added: list[str] | None = None
    columns_removed: list[str] | None = None
    columns_changed: list[ColumnChange] | None = None


class MetadataChange(BaseModel):
    field: str
    before: Any
    after: Any


class VersionDiff(BaseModel):
    from_version_id: Id | None
    to_version_id: Id
    summary: ChangeSummary
    files: list[FileChange]
    schema_: list[SchemaChange] = Field(..., alias='schema')
    metadata: list[MetadataChange]


class State(StrEnum):
    ADDED = 'ADDED'
    CHANGED = 'CHANGED'
    UNCHANGED = 'UNCHANGED'
    REMOVED = 'REMOVED'
    ABSENT = 'ABSENT'


class FileHistoryEntry(BaseModel):
    dataset_version_id: Id
    version_label: str
    published_at: AwareDatetime
    state: State
    sha256: str | None = None
    size_bytes: int | None = None


class FileHistory(BaseModel):
    dataset_id: Id
    path: str
    items: list[FileHistoryEntry]


class CitationStyle(StrEnum):
    text = 'text'
    bibtex = 'bibtex'
    datacite_json = 'datacite-json'


class DatasetCitation(BaseModel):
    dataset_version_id: Id
    style: CitationStyle
    content: str = Field(
        ..., description='datacite-json: a serialized DataCite 4.5 attributes object'
    )


class File(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: constr(pattern=r'^[A-Za-z0-9._/-]{1,512}$')
    size_bytes: conint(ge=1, le=53687091200) = Field(
        ..., description='P0 per-file limit 50 GiB'
    )
    sha256: constr(pattern=r'^[a-f0-9]{64}$')
    media_type: str


class UploadSessionCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    files: list[File] = Field(..., max_length=500, min_length=1)


class Status2(StrEnum):
    OPEN = 'OPEN'
    COMPLETED = 'COMPLETED'
    EXPIRED = 'EXPIRED'


class Upload(BaseModel):
    method: Literal['PUT']
    url: AnyUrl
    headers: dict[str, str] | None = None


class Part(BaseModel):
    part_number: int
    url: AnyUrl


class Upload1(BaseModel):
    method: Literal['MULTIPART']
    part_size_bytes: int
    parts: list[Part]


class File1(BaseModel):
    file_id: Id
    path: str
    status: FileStatus
    failure_code: str | None = None
    upload: Upload | Upload1 | None = None


class UploadSession(BaseModel):
    upload_session_id: Id
    dataset_version_id: Id
    status: Status2
    expires_at: Timestamp
    files: list[File1]


class DatasetSearchHit(BaseModel):
    dataset_id: Id
    title: str
    snippet: str | None = None
    owner_organization_id: Id
    owner_organization_name: str | None = None
    access_level: AccessLevel
    keywords: list[str] | None = None
    allowed_purposes: list[Purpose] | None = None
    latest_version_label: str | None = None
    readiness_overall: ReadinessOverall | None = None
    updated_at: Timestamp | None = None
    subtitle: str | None = None
    principal_investigator_name: str | None = None
    temporal_start: date_aliased | None = None
    temporal_end: date_aliased | None = None
    subject_codes: list[str] | None = None
    collecting_organization_name: str | None = None


class FacetBucket(BaseModel):
    value: str
    label: str | None = None
    count: int


class Facets(BaseModel):
    access_level: list[FacetBucket] | None = None
    owner_organization_id: list[FacetBucket] | None = None
    purpose: list[FacetBucket] | None = None
    keyword: list[FacetBucket] | None = None
    readiness_status: list[FacetBucket] | None = None
    subject: list[FacetBucket] | None = None
    collecting_organization_id: list[FacetBucket] | None = None
    material: list[FacetBucket] | None = None
    method: list[FacetBucket] | None = None


class DatasetSearchResult(PageEnvelope):
    items: list[Any]
    total: int
    facets: Facets


class AccessRequestCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dataset_id: Id
    project_id: Id
    purpose: Purpose
    purpose_detail: constr(min_length=20, max_length=4000)
    operations: list[Operation] = Field(..., min_length=1)
    requested_days: conint(ge=1, le=365)


class HistoryItem(BaseModel):
    status: AccessRequestStatus
    at: Timestamp
    by_user_id: Id | None = None
    comment: str | None = None


class AccessRequest(BaseModel):
    access_request_id: Id
    dataset_id: Id
    dataset_title: str | None = None
    project_id: Id
    project_name: str | None = None
    requester_user_id: Id
    requester_display_name: str | None = None
    requester_organization_id: Id
    owner_organization_id: Id
    purpose: Purpose
    purpose_detail: str
    operations: list[Operation]
    requested_days: int
    status: AccessRequestStatus
    history: list[HistoryItem] | None = None
    access_grant_id: Id | None = None
    created_at: Timestamp
    updated_at: Timestamp


class AccessApprove(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    grant_days: conint(ge=1, le=365) = Field(
        ...,
        description='<= requested_days and <= max_grant_days; expires_at = approved_at + grant_days',
    )
    operations: list[Operation] | None = Field(
        None,
        description='Subset of requested operations; default = requested',
        min_length=1,
    )
    note: constr(max_length=2000) | None = None


class AccessGrant(BaseModel):
    access_grant_id: Id
    access_request_id: Id | None = None
    subject_type: Literal['USER']
    subject_user_id: Id
    project_id: Id
    dataset_id: Id
    dataset_title: str | None = None
    subject_display_name: str | None = None
    project_name: str | None = None
    purpose: Purpose
    operations: list[Operation]
    valid_from: Timestamp
    expires_at: Timestamp
    granted_by: Id
    policy_version: str = Field(..., examples=['data_access@1.0.0'])
    status: AccessGrantStatus = Field(
        ...,
        description='Computed: ACTIVE with expires_at <= now is returned as EXPIRED',
    )
    revoked_at: AwareDatetime | None = None
    revoked_by: Id | None = None
    revocation_reason: str | None = None


class DownloadSessionCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    project_id: Id | None = Field(
        None,
        description='Required when basis would be GRANT (CONTROLLED/SENSITIVE for non-owner org)',
    )
    file_ids: list[Id] | None = Field(
        None,
        description='Default: all files of the version',
        max_length=500,
        min_length=1,
    )


class Basis(StrEnum):
    PUBLIC = 'PUBLIC'
    OWNER_ORGANIZATION = 'OWNER_ORGANIZATION'
    GRANT = 'GRANT'


class File2(BaseModel):
    file_id: Id
    path: str
    url: AnyUrl
    size_bytes: int
    sha256: str


class DownloadSession(BaseModel):
    dataset_version_id: Id
    basis: Basis
    access_grant_id: Id | None = None
    expires_at: Timestamp = Field(..., description='URL expiry (now + 300s)')
    files: list[File2]


class Severity(StrEnum):
    REQUIRED = 'REQUIRED'
    RECOMMENDED = 'RECOMMENDED'


class Check(BaseModel):
    check_id: str
    severity: Severity = Field(
        ...,
        description='REQUIRED FAIL => overall FAIL; RECOMMENDED FAIL => overall WARNING',
    )


class ReadinessProfile(BaseModel):
    profile_id: str
    version: str
    name: str
    description: str | None = None
    checks: list[Check]


class ReadinessCheckResult(BaseModel):
    check_id: str
    status: ReadinessCheckStatus
    severity: Severity
    message: str
    evidence: dict[str, Any] = Field(
        ..., description='Statistics/locations only, never raw values (D-018)'
    )


class Summary(BaseModel):
    pass_: int | None = Field(None, alias='pass')
    warning: int | None = None
    fail: int | None = None
    not_applicable: int | None = None


class TriggeredBy(StrEnum):
    AUTO_ON_PUBLISH = 'AUTO_ON_PUBLISH'
    USER = 'USER'


class ReadinessValidation(BaseModel):
    validation_id: Id
    dataset_version_id: Id
    profile_id: str
    profile_version: str
    run_status: ReadinessRunStatus
    overall_status: ReadinessOverall | None = None
    summary: Summary | None = None
    checks: list[ReadinessCheckResult] | None = None
    validator_version: str | None = None
    input_fingerprint: str | None = Field(
        None,
        description='sha256(manifest_sha256 + metadata_snapshot_sha256 + profile_id + profile_version + validator_version)',
    )
    error: str | None = Field(None, description='Set when run_status=FAILED')
    triggered_by: TriggeredBy | None = None
    created_at: Timestamp
    started_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None


class Result(StrEnum):
    SUCCESS = 'SUCCESS'
    DENIED = 'DENIED'


class Type1(StrEnum):
    USER = 'USER'
    SYSTEM = 'SYSTEM'


class Actor(BaseModel):
    type: Type1
    user_id: Id | None = None
    display_name: str | None = None
    organization_id: Id | None = None


class Resource(BaseModel):
    type: ResourceType
    id: Id
    owner_organization_id: Id | None = None


class AuditEvent(BaseModel):
    audit_event_id: Id
    occurred_at: Timestamp
    action: AuditAction
    result: Result
    reason: str | None = None
    actor: Actor
    resource: Resource
    project_id: Id | None = None
    policy_version: str | None = None
    source_event_id: Id
    source_event_type: str | None = None
    trace_id: str = Field(..., description='= source event correlation_id')
    details: dict[str, Any] | None = None


class Notification(BaseModel):
    notification_id: Id
    type: NotificationType
    title: str
    body: str | None = None
    link: str | None = Field(None, description='Web route, e.g. /commons/access/{id}')
    read: bool
    created_at: Timestamp


class DatasetActivityType(StrEnum):
    VERSION_PUBLISHED = 'VERSION_PUBLISHED'
    METADATA_CHANGED = 'METADATA_CHANGED'
    POLICY_CHANGED = 'POLICY_CHANGED'
    READINESS_COMPLETED = 'READINESS_COMPLETED'
    USED_IN_PROJECT = 'USED_IN_PROJECT'
    OUTPUT_PUBLISHED = 'OUTPUT_PUBLISHED'
    DISCUSSION_STARTED = 'DISCUSSION_STARTED'


class HubCard(BaseModel):
    dataset_id: Id
    title: str
    owner_organization_name: str
    subject_labels: list[str] = Field(
        ..., description='Korean SUBJECT vocabulary labels'
    )
    access_level: AccessLevel
    readiness_overall: ReadinessOverall | None = Field(
        ..., description='Same rule as DatasetVersionSummary.readiness_overall (D-028)'
    )
    updated_at: Timestamp
    metric: conint(ge=0) | None = Field(
        ...,
        description='trending = access requests in the last 7 days, most_used = project inputs, recent = null. Only real counts; null hides the figure.',
    )


class HubOrganizationStat(BaseModel):
    organization_id: Id
    name: str
    dataset_count: conint(ge=0)
    public_count: conint(ge=0)
    controlled_count: conint(ge=0) = Field(..., description='CONTROLLED + SENSITIVE')
    last_updated_at: AwareDatetime | None


class Rails(BaseModel):
    trending: list[HubCard] = Field(..., max_length=6)
    recent: list[HubCard] = Field(..., max_length=6)
    most_used: list[HubCard] = Field(..., max_length=6)


class HubOverview(BaseModel):
    rails: Rails
    organizations: list[HubOrganizationStat]


class DatasetProjectUse(BaseModel):
    project_id: Id
    name: str
    lead_organization_name: str
    input_added_at: Timestamp


class DatasetProjectsResult(BaseModel):
    items: list[DatasetProjectUse]
    hidden_count: conint(ge=0) = Field(
        ...,
        description='Projects using the dataset that the caller is not a member of (names hidden)',
    )


class DatasetActivity(BaseModel):
    activity_id: Id
    dataset_id: Id
    type: DatasetActivityType
    label: str | None = Field(
        ...,
        description='Entity label (version label, project name, output title, thread title); never data values',
    )
    ref_id: Id | None = Field(
        ..., description='Version, project, output or thread id for linking'
    )
    actor_display_name: str | None
    project_id: Id | None = Field(
        ..., description='Set only when the caller is a member of that project'
    )
    occurred_at: Timestamp


class RunStatus(StrEnum):
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'


class OutputKind(StrEnum):
    DERIVED_DATASET = 'DERIVED_DATASET'
    FILE = 'FILE'


class OutputPublishStatus(StrEnum):
    NONE = 'NONE'
    PENDING = 'PENDING'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    PUBLISHED = 'PUBLISHED'


class PublishRequestStatus(StrEnum):
    PENDING = 'PENDING'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'


class PublishDecision(StrEnum):
    APPROVE = 'APPROVE'
    REJECT = 'REJECT'


class ThreadScope(StrEnum):
    PROJECT = 'PROJECT'
    DATASET = 'DATASET'
    OUTPUT = 'OUTPUT'
    RECIPE = 'RECIPE'


class RecipeStepType(StrEnum):
    select_columns = 'select_columns'
    filter_rows = 'filter_rows'
    drop_missing = 'drop_missing'
    fill_missing = 'fill_missing'
    cast_type = 'cast_type'
    convert_unit = 'convert_unit'
    aggregate = 'aggregate'
    join = 'join'
    sort = 'sort'
    limit = 'limit'


class RecipeFilterOp(StrEnum):
    eq = 'eq'
    ne = 'ne'
    lt = 'lt'
    le = 'le'
    gt = 'gt'
    ge = 'ge'
    contains = 'contains'
    in_ = 'in'
    is_null = 'is_null'
    not_null = 'not_null'


class RecipeCastType(StrEnum):
    int = 'int'
    float = 'float'
    string = 'string'
    bool = 'bool'
    datetime = 'datetime'


class RecipeAggregateFn(StrEnum):
    count = 'count'
    sum = 'sum'
    mean = 'mean'
    min = 'min'
    max = 'max'


class RecipeJoinHow(StrEnum):
    inner = 'inner'
    left = 'left'


class ProjectInput(BaseModel):
    input_id: Id
    project_id: Id
    dataset_id: Id
    dataset_title: str
    dataset_version_id: Id = Field(..., description='Pinned version')
    version_label: str
    newer_version_label: str | None = Field(
        ..., description='Latest PUBLISHED label when newer than the pinned version'
    )
    access_level: AccessLevel
    access_lapsed: bool = Field(
        ...,
        description="true when the caller's access was revoked or expired; runs and downloads using it are blocked (INPUT_ACCESS_LAPSED)",
    )
    added_by: Id
    added_by_display_name: str
    added_at: Timestamp
    note: str | None


class ProjectInputCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dataset_id: Id
    dataset_version_id: Id | None = Field(
        None, description='Default: latest PUBLISHED version'
    )
    note: constr(max_length=2000) | None = None


class ProjectInputUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dataset_version_id: Id | None = None
    note: constr(max_length=2000) | None = None


class Column(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class RecipeStepSelectColumns(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['select_columns']
    columns: list[Column] = Field(..., min_length=1)


class RecipeStepFilterRows(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['filter_rows']
    column: constr(min_length=1)
    op: RecipeFilterOp
    value: str | int | float | bool | list[str | int | float] | None = Field(
        None, description='Required except for is_null/not_null; an array for in'
    )


class RecipeStepDropMissing(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['drop_missing']
    columns: list[constr(min_length=1)] | None = Field(
        ..., description='null = any column'
    )


class RecipeStepFillMissing(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['fill_missing']
    column: constr(min_length=1)
    value: str | int | float | bool


class RecipeStepCastType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['cast_type']
    column: constr(min_length=1)
    to: RecipeCastType


class RecipeStepConvertUnit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['convert_unit']
    column: constr(min_length=1)
    factor: float = Field(..., description='new = old * factor + offset')
    offset: float
    unit_label: constr(min_length=1, max_length=32)


class Metric(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    column: constr(min_length=1)
    fn: RecipeAggregateFn


class RecipeStepAggregate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['aggregate']
    group_by: list[constr(min_length=1)]
    metrics: list[Metric] = Field(..., min_length=1)


class OnItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class RecipeStepJoin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['join']
    right_input_id: Id = Field(..., description="Must be one of the recipe's input_ids")
    on: list[OnItem] = Field(..., min_length=1)
    how: RecipeJoinHow


class ByItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class RecipeStepSort(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['sort']
    by: list[ByItem] = Field(..., min_length=1)
    descending: bool


class RecipeStepLimit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['limit']
    n: conint(ge=1, le=5000000)


class RecipeStep(
    RootModel[
        RecipeStepSelectColumns
        | RecipeStepFilterRows
        | RecipeStepDropMissing
        | RecipeStepFillMissing
        | RecipeStepCastType
        | RecipeStepConvertUnit
        | RecipeStepAggregate
        | RecipeStepJoin
        | RecipeStepSort
        | RecipeStepLimit
    ]
):
    root: (
        RecipeStepSelectColumns
        | RecipeStepFilterRows
        | RecipeStepDropMissing
        | RecipeStepFillMissing
        | RecipeStepCastType
        | RecipeStepConvertUnit
        | RecipeStepAggregate
        | RecipeStepJoin
        | RecipeStepSort
        | RecipeStepLimit
    ) = Field(..., discriminator='type')


class Recipe(BaseModel):
    recipe_id: Id
    project_id: Id
    name: str
    input_ids: list[Id] = Field(
        ..., description='First id is the base table; join steps reference the others'
    )
    steps: list[RecipeStep]
    version: conint(ge=1) = Field(
        ..., description='+1 on every save; send as If-Match on updateRecipe'
    )
    updated_by: Id
    updated_at: Timestamp


class RecipeWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=200)
    input_ids: list[Id] = Field(..., max_length=10, min_length=1)
    steps: list[RecipeStep] = Field(..., max_length=50)


class RecipePreviewRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_ids: list[Id] | None = Field(None, max_length=10, min_length=1)
    steps: list[RecipeStep] | None = Field(None, max_length=50)


class RecipePreview(BaseModel):
    header: list[str]
    rows: list[list[constr(max_length=200) | None]] = Field(..., max_length=100)
    rows_truncated: bool = Field(..., description='More than 100 result rows')
    input_rows_read: conint(ge=0) = Field(
        ..., description='Rows read from the inputs (≤ 10,000 per input)'
    )
    output_rows: conint(ge=0) = Field(
        ..., description='Result rows of the sampled inputs'
    )


class Run(BaseModel):
    run_id: Id
    project_id: Id
    recipe_id: Id
    recipe_version: conint(ge=1)
    status: RunStatus
    started_by: Id
    queued_at: Timestamp
    started_at: AwareDatetime | None
    finished_at: AwareDatetime | None
    input_rows: conint(ge=0) | None
    output_rows: conint(ge=0) | None
    error: str | None = Field(
        ...,
        description='Stable failure code when FAILED (RECIPE_MISSING, INPUT_ACCESS_LAPSED, RECIPE_INVALID, RESULT_TOO_LARGE, INPUT_UNAVAILABLE, INPUT_NOT_TABULAR, INPUT_TOO_LARGE, INPUT_UNREADABLE, STORAGE_NOT_CONFIGURED, OUT_OF_MEMORY, STORAGE_UNAVAILABLE, INTERNAL_ERROR, RUN_TIMEOUT, STALE_RUN). Clients show a localized sentence and a generic one for an unknown code; the detail is only logged.',
        examples=['INPUT_TOO_LARGE'],
    )
    output_id: Id | None = Field(
        ..., description='DERIVED_DATASET output when SUCCEEDED'
    )


class OutputFile(BaseModel):
    name: str
    size_bytes: conint(ge=0)
    sha256: constr(pattern=r'^[a-f0-9]{64}$')
    media_type: str


class OutputLineageInput(BaseModel):
    dataset_id: Id
    dataset_title: str
    dataset_version_id: Id
    version_label: str


class OutputLineage(BaseModel):
    inputs: list[OutputLineageInput]
    recipe_id: Id | None
    recipe_version: conint(ge=1) | None
    run_id: Id | None


class Output(BaseModel):
    output_id: Id
    project_id: Id
    kind: OutputKind
    title: str
    access_level: AccessLevel = Field(
        ..., description='Never looser than the strictest lineage input'
    )
    files: list[OutputFile]
    produced_by_run_id: Id | None = Field(
        ..., description='null for uploaded FILE outputs'
    )
    lineage: OutputLineage
    publish_status: OutputPublishStatus
    created_by: Id
    created_at: Timestamp


class File3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(pattern=r'^[A-Za-z0-9._-]{1,255}$') = Field(
        ..., description='Flat file name, no path'
    )
    size_bytes: conint(ge=1, le=5368709120) = Field(
        ..., description='Single presigned PUT: ≤ 5 GiB'
    )
    sha256: constr(pattern=r'^[a-f0-9]{64}$')
    media_type: str


class OutputUploadCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: constr(min_length=1, max_length=300)
    access_level: AccessLevel
    files: list[File3] = Field(..., max_length=20, min_length=1)


class Upload2(BaseModel):
    method: Literal['PUT']
    url: AnyUrl
    headers: dict[str, str] | None = None


class File4(BaseModel):
    name: str
    upload: Upload2


class OutputUploadSession(BaseModel):
    output_id: Id
    expires_at: Timestamp = Field(..., description='now + 15 min')
    files: list[File4]


class File5(BaseModel):
    name: str
    url: AnyUrl
    size_bytes: int
    sha256: str


class OutputDownload(BaseModel):
    output_id: Id
    expires_at: Timestamp = Field(..., description='URL expiry (now + 300s)')
    files: list[File5]


class PublishApproval(BaseModel):
    organization_id: Id
    organization_name: str | None = None
    decided_by: Id | None
    decision: PublishDecision | None
    comment: str | None
    decided_at: AwareDatetime | None


class PublishRequest(BaseModel):
    request_id: Id
    output_id: Id
    project_id: Id
    status: PublishRequestStatus
    approvals: list[PublishApproval] = Field(
        ...,
        description='One slot per owner organization of the lineage inputs, then the project lead organization when it owns none of them (only the lead organization for an output without inputs); each decided by a DATA_STEWARD of that organization',
        min_length=1,
    )
    created_by: Id
    created_at: Timestamp
    output_title: str | None = None
    project_name: str | None = None
    published_dataset_id: Id | None = Field(
        None, description='Catalog dataset created once APPROVED'
    )
    failure_reason: str | None = Field(
        None,
        description='Set when an APPROVED request could not be published by the catalog and was turned REJECTED by the system (human-readable, no data values)',
    )


class PublishRequestCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: constr(min_length=3, max_length=300) | None = Field(
        None, description='Dataset title; default = output title'
    )
    description: constr(max_length=20000) | None = None


class PublishDecisionCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decision: PublishDecision
    comment: constr(max_length=2000) | None = Field(
        None, description='Required (minLength 1) for REJECT; enforced by the server'
    )


class Thread(BaseModel):
    thread_id: Id
    scope: ThreadScope
    target_id: Id = Field(
        ..., description='project_id, dataset_id, output_id or recipe_id per scope'
    )
    project_id: Id | None = Field(..., description='null for DATASET threads')
    title: str
    created_by: Id
    created_by_display_name: str
    created_at: Timestamp
    resolved: bool
    comment_count: conint(ge=1)
    last_comment_at: Timestamp


class ThreadCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scope: ThreadScope
    target_id: Id
    title: constr(min_length=1, max_length=200)
    body: constr(min_length=1, max_length=10000) = Field(..., description='Markdown')


class ThreadUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    resolved: bool | None = None
    title: constr(min_length=1, max_length=200) | None = None


class Comment(BaseModel):
    comment_id: Id
    thread_id: Id
    body: str = Field(..., description='Markdown')
    author_id: Id
    author_display_name: str
    created_at: Timestamp
    edited_at: AwareDatetime | None


class CommentCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    body: constr(min_length=1, max_length=10000) = Field(..., description='Markdown')


class NoteStatus(StrEnum):
    DRAFT = 'DRAFT'
    SUBMITTED = 'SUBMITTED'
    SIGNED = 'SIGNED'


class NoteDraftStatus(StrEnum):
    NONE = 'NONE'
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    FAILED = 'FAILED'
    DONE = 'DONE'


class NoteSection(StrEnum):
    OBJECTIVE = 'OBJECTIVE'
    METHOD = 'METHOD'
    PROCEDURE = 'PROCEDURE'
    RESULTS = 'RESULTS'
    DISCUSSION = 'DISCUSSION'
    NEXT = 'NEXT'
    REFERENCES = 'REFERENCES'


class NoteBlockOrigin(StrEnum):
    HUMAN = 'HUMAN'
    AI = 'AI'


class NoteSignerRole(StrEnum):
    RECORDER = 'RECORDER'
    WITNESS = 'WITNESS'


class NoteEvidenceType(StrEnum):
    INPUT_ADDED = 'INPUT_ADDED'
    INPUT_VERSION_CHANGED = 'INPUT_VERSION_CHANGED'
    RECIPE_SAVED = 'RECIPE_SAVED'
    RUN_SUCCEEDED = 'RUN_SUCCEEDED'
    RUN_FAILED = 'RUN_FAILED'
    OUTPUT_CREATED = 'OUTPUT_CREATED'
    PUBLISH_REQUESTED = 'PUBLISH_REQUESTED'
    DATASET_DOWNLOADED = 'DATASET_DOWNLOADED'
    ACCESS_DECIDED = 'ACCESS_DECIDED'
    NOTEBOOK = 'NOTEBOOK'


class NoteEvidence(BaseModel):
    type: NoteEvidenceType
    ref_id: Id = Field(
        ...,
        description='Input, recipe, run, output, publish request, dataset version or access request id; for NOTEBOOK the notebook version id (the notebook id when unversioned)',
    )
    label: str = Field(
        ...,
        description='Entity label only (dataset title@version, recipe name, row counts, notebook title · cell k); never data values',
    )
    at: Timestamp


class NoteBlock(BaseModel):
    block_id: Id
    section: NoteSection
    text: str
    origin: NoteBlockOrigin
    accepted: bool = Field(
        ...,
        description='AI blocks start false; submit/sign require every AI block accepted',
    )
    evidence: list[NoteEvidence]


class NoteBlockWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    block_id: Id | None = Field(
        None,
        description='Existing block (keeps origin and evidence); omit for a new HUMAN block',
    )
    section: NoteSection
    text: constr(min_length=1, max_length=4000)
    accepted: bool | None = Field(
        None,
        description='Accepting an AI block; ignored for HUMAN blocks (always true)',
    )


class NoteBlocksPut(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blocks: list[NoteBlockWrite] = Field(..., max_length=500)


class NoteSignature(BaseModel):
    signer_id: Id
    signer_display_name: str
    role: NoteSignerRole
    signed_at: Timestamp = Field(..., description='Server time')
    content_hash: constr(pattern=r'^[a-f0-9]{64}$')


class ResearchNote(BaseModel):
    note_id: Id
    project_id: Id
    project_name: str
    organization_id: Id = Field(
        ...,
        description="Recorder's organization when the note was created; never changes (지침 제8·9조)",
    )
    recorder_id: Id
    recorder_display_name: str
    note_date: date_aliased = Field(..., description='Asia/Seoul date')
    version: conint(ge=1)
    previous_version_id: Id | None
    status: NoteStatus
    revision: conint(ge=1) = Field(
        ..., description='+1 on every block save; send as If-Match on updateNoteBlocks'
    )
    blocks: list[NoteBlock]
    draft_status: NoteDraftStatus
    draft_error: str | None
    draft_source_count: conint(ge=0) = Field(
        ...,
        description='Notebooks the recorder saved in this project on note_date (the drafting source); shown to the recorder only, 0 for everyone else. 0 -> draftNote answers 422 NO_NOTEBOOK_ACTIVITY',
    )
    signatures: list[NoteSignature]
    content_hash: constr(pattern=r'^[a-f0-9]{64}$') | None = Field(
        ...,
        description='sha256 of the canonical JSON of content + metadata; set on submit/sign, cleared when a witness rejects the note back to DRAFT',
    )
    chain_hash: constr(pattern=r'^[a-f0-9]{64}$') | None = Field(
        ...,
        description='sha256(previous chain_hash + content_hash) per project × organization; set when SIGNED',
    )
    submitted_at: AwareDatetime | None
    rejected_reason: str | None
    witness_required: bool = Field(
        ...,
        description='Snapshot of the project setting taken at submit (or at a sign from DRAFT). signNote/rejectNote use this, never the current setting. While DRAFT it mirrors the current setting for display and is re-taken at the next submit.',
    )
    witness_user_ids: list[Id] = Field(
        ...,
        description='Witness snapshot taken together with witness_required; these users may read, reject and sign the SUBMITTED/SIGNED note',
    )
    created_at: Timestamp
    updated_at: Timestamp


class ResearchNoteSummary(BaseModel):
    note_id: Id
    project_id: Id
    project_name: str
    recorder_id: Id
    recorder_display_name: str
    note_date: date_aliased
    version: conint(ge=1)
    status: NoteStatus
    draft_status: NoteDraftStatus
    block_count: conint(ge=0)
    unaccepted_ai_count: conint(ge=0) | None = None
    submitted_at: AwareDatetime | None = None
    updated_at: Timestamp


class NoteVerification(BaseModel):
    note_id: Id
    valid: bool = Field(..., description='content_hash == recomputed_hash')
    content_hash: constr(pattern=r'^[a-f0-9]{64}$')
    recomputed_hash: constr(pattern=r'^[a-f0-9]{64}$')
    chain_valid: bool = Field(
        ...,
        description='Rebuilt project × organization chain matches the stored chain_hash values',
    )
    checked_at: Timestamp


class NoteSearchHit(BaseModel):
    note_id: Id
    project_name: str
    note_date: date_aliased
    snippet: str
    score: float | None = Field(
        ..., description='Rerank/cosine score; null for keyword fallback'
    )


class NoteSettings(BaseModel):
    project_id: Id
    witness_required: bool
    witness_user_ids: list[Id]
    llm_enabled: bool = Field(
        ...,
        description='Server setting NAIS_LLM_ENABLED; hides the draft button when false',
    )


class NoteSettingsUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    witness_required: bool | None = None
    witness_user_ids: list[Id] | None = Field(None, max_length=20)


class Dataset(BaseModel):
    dataset_id: Id
    owner_organization_id: Id
    owner_organization_name: str | None = None
    title: str
    description: str
    keywords: list[str] | None = None
    domain: str | None = None
    access_level: AccessLevel
    license: str
    usage_policy: str | None = None
    contact_email: str | None = None
    provenance: str | None = None
    policy: DatasetPolicyView
    status: DatasetStatus
    latest_published_version: DatasetVersionSummary | None = None
    created_by: Id | None = None
    created_at: Timestamp
    updated_at: Timestamp
    subtitle: str | None = None
    people: DatasetPeople | None = None
    contact_email_public: bool | None = None
    project_title: str | None = None
    project_code: str | None = None
    funding_agency: str | None = None
    subject_codes: list[str] | None = None
    method_codes: list[str] | None = None
    material_codes: list[str] | None = None
    method_detail: str | None = None
    temporal_start: date_aliased | None = None
    temporal_end: date_aliased | None = None
    collecting_organization: OrganizationRef | None = None
    update_frequency: UpdateFrequency | None = None
    related_publications: list[RelatedPublication] | None = None
    stats: Stats | None = Field(
        None, description='Derived from the latest published version (no input)'
    )


class DatasetVersion(DatasetVersionSummary):
    dataset_id: Id
    change_note: str | None = None
    files: list[DatasetFile]
    file_count: int
    total_bytes: int
    manifest_sha256: str | None = Field(
        None,
        description="sha256 over sorted 'path\\tsize\\tsha256' lines; set on publish",
    )
    created_at: Timestamp
    created_by: Id | None = None
    base_version_id: Id | None = None
    source_version_id: Id | None = None
    previous_version_id: Id | None = None
    base_is_latest: bool | None = Field(
        None,
        description='DRAFT only: base_version_id is the latest PUBLISHED version (publishable without rebase)',
    )
    change_summary: ChangeSummary | None = None


class AccessDecisionResult(BaseModel):
    access_request: AccessRequest
    access_grant: AccessGrant | None = None
