"""Regenerate code from NAIS_PRD/contracts.

Usage:
    uv run python packages/contracts/generate.py            # write files
    uv run python packages/contracts/generate.py --check    # exit 1 if any generated file is stale
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from collections.abc import Callable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTRACTS = ROOT / "NAIS_PRD" / "contracts"
OPENAPI = CONTRACTS / "openapi.yaml"
HEADER = "# GENERATED by packages/contracts/generate.py from NAIS_PRD/contracts/{source} - do not edit.\n"


def render_error_codes() -> str:
    codes = json.loads((CONTRACTS / "error_codes.json").read_text(encoding="utf-8"))["codes"]
    out = [HEADER.format(source="error_codes.json"), "from enum import StrEnum\n\n\nclass ErrorCode(StrEnum):\n"]
    out += [f'    {c["code"]} = "{c["code"]}"\n' for c in codes]
    out.append("\n\nHTTP_STATUS: dict[ErrorCode, int] = {\n")
    out += [f'    ErrorCode.{c["code"]}: {c["http"]},\n' for c in codes]
    out.append("}\n\nDESCRIPTION: dict[ErrorCode, str] = {\n")
    out += [f'    ErrorCode.{c["code"]}: {json.dumps(c["description"], ensure_ascii=False)},\n' for c in codes]
    out.append("}\n")
    return "".join(out)


def render_event_types() -> str:
    events = json.loads((CONTRACTS / "events" / "index.json").read_text(encoding="utf-8"))["events"]

    def member(event_type: str) -> str:
        return event_type.upper().replace(".", "_")

    out = [HEADER.format(source="events/index.json"), "from enum import StrEnum\n\n\nclass EventType(StrEnum):\n"]
    out += [f'    {member(e["event_type"])} = "{e["event_type"]}"\n' for e in events]
    out.append("\n\nPRODUCER: dict[EventType, str] = {\n")
    out += [f'    EventType.{member(e["event_type"])}: "{e["producer"]}",\n' for e in events]
    out.append("}\n")
    return "".join(out)


def run_datamodel_codegen(target: Path) -> None:
    subprocess.run(
        [
            sys.executable, "-m", "datamodel_code_generator",
            "--input", str(OPENAPI), "--input-file-type", "openapi",
            "--output-model-type", "pydantic_v2.BaseModel", "--target-python-version", "3.13",
            "--use-standard-collections", "--use-union-operator", "--disable-timestamp",
            "--output", str(target),
        ],
        check=True,
        capture_output=True,
    )


def run_openapi_typescript(target: Path) -> None:
    subprocess.run(
        ["npx", "--yes", "openapi-typescript@7.13.0", str(OPENAPI), "-o", str(target)],
        check=True,
        capture_output=True,
    )


TEXT_TARGETS: dict[str, Callable[[], str]] = {
    "apps/api/platform/generated/error_codes.py": render_error_codes,
    "apps/api/platform/generated/event_types.py": render_event_types,
}
TOOL_TARGETS: dict[str, Callable[[Path], None]] = {
    "packages/contracts/python/nais_contracts/api_models.py": run_datamodel_codegen,
    "packages/contracts/ts/openapi.d.ts": run_openapi_typescript,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args(argv)
    stale: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        for rel, render in TEXT_TARGETS.items():
            scratch = Path(tmp) / Path(rel).name
            scratch.write_text(render(), encoding="utf-8")
            stale += _sync(rel, scratch, check=args.check)
        for rel, tool in TOOL_TARGETS.items():
            scratch = Path(tmp) / Path(rel).name
            tool(scratch)
            stale += _sync(rel, scratch, check=args.check)
    if stale:
        print("stale generated files:\n  " + "\n  ".join(stale))
        print("run: uv run python packages/contracts/generate.py")
        return 1
    print("generated files are up to date" if args.check else "generated files written")
    return 0


def _sync(rel: str, scratch: Path, *, check: bool) -> list[str]:
    target = ROOT / rel
    fresh = scratch.read_bytes()
    if target.exists() and target.read_bytes() == fresh:
        return []
    if check:
        return [rel]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(fresh)
    return []


if __name__ == "__main__":
    raise SystemExit(main())
